<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Atlas.Shared.csproj" />
    <ProjectReference Include="..\Observability\Atlas.Modules.Observability.csproj" />
  </ItemGroup>
</Project>
