// <auto-generated />
using System;
using Atlas.Modules.Observability.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Atlas.Modules.Observability.Infrastructure.Migrations
{
    [DbContext(typeof(ObservabilityDbContext))]
    [Migration("20261004110253_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("observability")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Atlas.Modules.Observability.Domain.MetricSample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeploymentVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("MetricType")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("bytea");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("Success")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "ServiceId", "DeploymentVersion", "RecordedAtUtc");

                    b.HasIndex("OrganizationId", "ServiceId", "MetricType", "RecordedAtUtc");

                    b.ToTable("MetricSamples", "observability");
                });

            modelBuilder.Entity("Atlas.Modules.Observability.Domain.RequestTelemetryAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ClientErrorCount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeploymentVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.PrimitiveCollection<long[]>("DurationBucketCounts")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<double>("MaxDurationMs")
                        .HasColumnType("double precision");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<long>("RequestCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("bytea");

                    b.Property<long>("ServerErrorCount")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<double>("TotalDurationMs")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("WindowStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "WindowStartUtc");

                    b.HasIndex("OrganizationId", "ServiceId", "WindowStartUtc");

                    b.HasIndex("OrganizationId", "ServiceId", "Route", "HttpMethod", "DeploymentVersion", "WindowStartUtc")
                        .IsUnique();

                    b.ToTable("RequestTelemetryAggregates", "observability");
                });

            modelBuilder.Entity("Atlas.Modules.Observability.Domain.ServiceLevelObjective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MetricType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("bytea");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<double>("TargetValue")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("WindowDuration")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "ServiceId");

                    b.ToTable("ServiceLevelObjectives", "observability");
                });
#pragma warning restore 612, 618
        }
    }
}
