<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.PostgreSQL" Version="9.0.0" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.9.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.9.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Atlas.Shared.csproj" />
  </ItemGroup>
</Project>
